name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: bearts
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker buildx build --push \
        --tag bearts/cryptoclique:latest \
        --platform linux/amd64 .